def generate_vpc_tf(cidr_block, subnet_count, output_file):
    """
    Generates a generic main.tf for a VPC with N subnets.
    """
    print(f"[*] Generating Terraform configuration...")
    print(f"[*] CIDR: {cidr_block}")
    print(f"[*] Subnets: {subnet_count}")
    
    tf_content = f"""
# Generated by EricYoung Labs VPC Generator

provider "aws" {{
  region = "us-east-1"
}}

resource "aws_vpc" "main" {{
  cidr_block = "{cidr_block}"
  tags = {{
    Name = "Generated-VPC"
  }}
}}
"""

    # Generate subnets
    # Simple logic: increment the third octet for each subnet
    # Assumes /16 or /24 input mostly, doing a naive split
    base_ip = cidr_block.split('/')[0]
    octets = base_ip.split('.')
    
    for i in range(subnet_count):
        # Calculate a simple CIDR for the subnet (e.g., 10.0.1.0/24)
        # This is invalid if the base CIDR is too small, but fine for a "lab tool"
        subnet_cidr = f"{octets[0]}.{octets[1]}.{i+1}.0/24"
        
        subnet_block = f"""
resource "aws_subnet" "subnet_{i+1}" {{
  vpc_id     = aws_vpc.main.id
  cidr_block = "{subnet_cidr}"
  tags = {{
    Name = "Subnet-{i+1}"
  }}
}}
"""
        tf_content += subnet_block

    with open(output_file, "w") as f:
        f.write(tf_content)
        
    print(f"[+] Configuration saved to {output_file}")
